---    
  - name: download multus git repo
    git:
      repo: "https://github.com/intel/multus-cni.git"
      dest: ../build/multus-cni
      version: "v3.8"
      
  - name: install multus
    shell: kubectl apply -f ../build/multus-cni/images/multus-daemonset.yml
    register: response
    failed_when: "response.rc != 0 and 'already exist' not in response.stderr"
  
  - name: Create SRIOV config map
    shell: kubectl apply -f ../build/sriovdp_cm.yaml

  - name: download multus sriov cni git repo
    git:
      repo: "https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin"
      dest: ../build/sriov-network-device-plugin
      version: "v3.3.2"

  - name: install sriov multus daemonset
    shell: kubectl apply -f ../build/sriov-network-device-plugin/deployments/k8s-v1.16/sriovdp-daemonset.yaml
    register: response
    failed_when: "response.rc != 0 and 'already exist' not in response.stderr"

  - name: debug output
    debug:
      msg: "{{ response }}"

  