---    
  - name: download helm
    get_url:
      url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
      dest: ./get_helm.sh
      mode: 0755

  - name: install helm
    shell: ./get_helm.sh

  - name: add helm stable repo
    community.kubernetes.helm_repository:
      name: stable
      repo_url: https://charts.helm.sh/stable

  - name: add helm paco repo
    community.kubernetes.helm_repository:
      name: "{{harbor.name}}"
      repo_url: "{{harbor.url}}"
      repo_username: "{{harbor.username}}"
      repo_password: "{{harbor.secret}}"

  - name: add helm repo
    shell: helm repo add {{harbor.name}} {{harbor.url}} --username '{{harbor.username}}' --password '{{harbor.secret}}'

  - name: helm repo update
    shell: helm repo update
  
  - name: create charts directory
    file:
      path: charts
      state: directory
      mode: 0755
      