---
  - name: add ansible repo
    apt_repository:
      repo: ppa:ansible/ansible
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"

  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"

  - name: install  packages
    apt:
      name: "{{ item.pkgname }}"
      state: present
    with_items:
      # - { pkgname: "ntp" }
      # - { pkgname: "ntpstat" }
      # - { pkgname: "ntpdate" }
      # - { pkgname: "ntpsec-ntpdate" }
      # - { pkgname: "bridge-utils" }
      # - { pkgname: "python3"}
      # - { pkgname: "python3-setuptools"}
      - { pkgname: "python3-pip"}
      # - { pkgname: "python3-dev"}
      # - { pkgname: "build-essential"}
      # - { pkgname: "golang" }
      # - { pkgname: "git"}
      # - { pkgname: "ansible"}
      # - { pkgname: "sshpass"}
      # - { pkgname: "whois"}
      # - { pkgname: "openjdk-11-jdk"}
      # - { pkgname: "openjdk-11-jre"}
      # - { pkgname: "bind9"}
      # - { pkgname: "dnsutils"}
      # - { pkgname: "linux-tools-common"}
      # - { pkgname: "nghttp2-client"}
      # - { pkgname: "arping"}
      # - { pkgname: "unzip"}
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
  
  - name: Upgrade all packages on ubuntu
    apt:
      name: "*"
      state: latest
  
  - name: Update all packages on ubuntu
    apt:
      upgrade: dist
  
