- name: Disable auto upgrade on Debian
  copy:
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    content: |
      APT::Periodic::Update-Package-Lists "0";
      APT::Periodic::Download-Upgradeable-Packages "0";
      APT::Periodic::AutocleanInterval "0";
      APT::Periodic::Unattended-Upgrade "0";