---
    - name: Disable SELinux on centos
      selinux:
        state: disabled
    
    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent
    
    - name: Disable swap
      command: swapoff -a
    
    - name: Add br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
    
    - name: create file /etc/sysctl.d/99-kubernetes-cri.conf
      file:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        state: touch
    
    - name: add sysctl /etc/sysctl.d/99-kubernetes-cri.conf
      blockinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        marker: ""
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
    - name: sysctl --system
      command: sysctl --system
    
    # - name: Check if EPEL repo is already configured.
    #   stat: 
    #     path: "/etc/yum.repos.d/cbs.centos.org_repos_paas7-crio-311-candidate_x86_64_os_.repo"
    #   register: crio_repofile_result
    
    # - name: Add crio repository
    #   command: yum-config-manager --add-repo=https://cbs.centos.org/repos/paas7-crio-311-candidate/x86_64/os/
    #   when: not crio_repofile_result.stat.exists
    
    # - name: install cri-o
    #   yum: 
    #     name: {{ item.pkgname }}
    #     state: "present"
    #     disable_gpg_check: yes
    #   with_items:
    #     - { pkgname: "cri-o", state: "present"  }
    
    # - name: cri-o restart
    #   systemd:
    #     state: restarted
    #     name: cri-o
    
    # Kubernetes Repo's
    
    - name: Check if kubernetes repo is already configured.
      stat: 
        path: "/etc/yum.repos.d/kubernetes.repo"
      register: kubernetes_repofile_result
    
    - name: ensure kubernetes.repo exists
      copy:
        content: ""
        dest: /etc/yum.repos.d/kubernetes.repo
        force: no
        group: root
        owner: root
        mode: 0644
      when: not kubernetes_repofile_result.stat.exists
    
    - name: insert items in kubernetes.repo file
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        marker: ""
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=0
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      when: not kubernetes_repofile_result.stat.exists
    
    - name: install kubernetes packages
      yum: 
        name: "{{ item.pkgname }}"
        state: "present"
        update_cache: yes
        allow_downgrade: yes
      with_items:
        - { pkgname: "kubelet-{{kube_version}}", state: "present"  }
        - { pkgname: "kubeadm-{{kube_version}}", state: "present"  }
        - { pkgname: "kubectl-{{kube_version}}", state: "present"  }