---
- name: install golang
  include_role:
    name: gantsign.golang
- name: clone latest paco-parser
  ansible.builtin.git:
    repo: https://github.com/nokia-paco-automation/paco-parser.git
    dest: /tmp/paco-parser
    single_branch: yes
    version: templating-test
- name: run paco-parser
  ansible.builtin.command: 
    argv:
      - go run /tmp/paco-parser/*.go -c {{ CWD }}/input.yaml -o {{ CWD }}/build/paco-parser parse
