- name: Set SRIOV VFs if using netplan
  copy:
    dest: "/etc/networkd-dispatcher/carrier.d/10-sriov-vf"
    mode: "0744"
    content: |
      #!/bin/sh


- name: Set SRIOV if using netplan
  lineinfile:
    path: "/etc/networkd-dispatcher/carrier.d/10-sriov-vf"
    line: echo '{{ num_sriov_vfs }}' > "/sys/class/net/{{item}}/device/sriov_numvfs"
    state: present

  with_items: "{{hostvars[inventory_hostname].eth_name}}"
      
