- name: Create list of SRIOV interfaces
  set_fact: sriov_int="{{sriov_int | default([]) + item.eth_name}}"
  #when: item.sriov
  with_items:
    - "{{ interfaces }}"

- name: debug sriov_int
  debug:
    msg: "{{ sriov_int }}"

- name: create SRIOV script
  template:
    src: enableSRIOV.sh.j2
    dest: "/usr/local/bin/enableSRIOV.sh"
    mode: 0744

- name: Set SRIOV script via systemd service
  become: true
  copy:
     dest: "/etc/systemd/system/sriov.service"
     mode: "0744"
     content: |
       [Unit]
       Description=Script to enable SR-IOV on boot

       [Service]
       Type=oneshot
       ExecStart=/usr/local/bin/enableSRIOV.sh
       
       [Install]
       WantedBy=multi-user.target
       Before=kubelet.service

- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable sriov service
  become: true
  ansible.builtin.systemd:
    name: sriov.service
    state: started
    enabled: yes
   
