#- name: Check if kernel src is present
#  stat:
#    path: "/usr/src/kernels/{{ ansible_kernel }}"
#  register: kernel_src

#- name: Download kernel src
#  get_url:
#    url: "https://www.rpmfind.net/linux/centos/8.1.1911/BaseOS/x86_64/os/Packages/kernel-devel-{{ ansible_kernel }}.rpm"
#    dest: "/tmp/kernel-devel-{{ ansible_kernel }}.rpm"
#    timeout: 60
#  retries: 5
#  delay: 1
#  register: result
#  until: result is succeeded and  result.size > 10240
#  when: "not kernel_src.stat.exists"

#- name: Install kernel src
#  dnf:
#    name: "/tmp/kernel-devel-{{ ansible_kernel }}.rpm"
#    state: present
#  when: "not kernel_src.stat.exists"

#- name: Download kernel mod
#  get_url:
#    url: "https://rpmfind.net/linux/centos/8.1.1911/BaseOS/x86_64/os/Packages/kernel-modules-{{ ansible_kernel }}.rpm"
#    dest: "/tmp/kernel-modules-{{ ansible_kernel }}.rpm"
#    timeout: 60
#  retries: 5
#  delay: 1
#  register: result
#  until: result is succeeded and  result.size > 10240

#- name: Install kernel mod
#  dnf:
#    name: "/tmp/kernel-modules-{{ ansible_kernel }}.rpm"
#    state: present

#- name: Enable NetworkManager-dispatcher
#  systemd:
#    enabled: true
#    name: NetworkManager-dispatcher
#    state: started

- name: Create list of SRIOV interfaces
  set_fact: sriov_int="{{sriov_int | default([]) + item.eth_name}}"
  when: item.sriov
  with_items:
    - "{{ interfaces }}"

      #- name: Enable SRIOV VFs
      #shell: "echo {{ num_sriov_vfs }} > /sys/class/net/{{item}}/device/sriov_numvfs"
      #with_items:
      #- "{{ sriov_int }}"

- name: Set SRIOV VFs persistent via systemd service
  copy:
     dest: "/etc/systemd/system/sriov.service"
     mode: "0744"
     content: |
       [Unit]
       Description=Script to enable SR-IOV on boot

       [Service]
       Type=oneshot
       ExecStart=/usr/bin/bash -c '/usr/bin/echo {{ num_sriov_vfs }} > /sys/class/net/{{item}}/device/sriov_numvfs'

       [Install]
       WantedBy=multi-user.target
       Before=kubelet.service
  with_items:
    - "{{ sriov_int }}"
   
