- include: paco-prepare.yaml sw="{{item}}"
  with_items: "{{ paco_sw.elements}}"

- name: Create values.yaml file per app
  template: 
    src: "{{ item }}.j2"
    dest: "../build/{{ item }}"
  with_items:
#    - values_amf.yaml
#    - values_smf.yaml
    - values_upfscale.yaml

