- name: create anthos install directory
  file:
    path: ~/{{anthos_dir}}
    state: directory
    mode: 0755

- name: download bmctl
  shell: gsutil cp gs://anthos-baremetal-release/bmctl/{{anthos_version}}/linux-amd64/bmctl ~/{{anthos_dir}}/bmctl

- name: change permission bmctl
  file:
    path: ~/{{anthos_dir}}/bmctl
    mode: 0755
