---
  - name: Create storage class file
    template: 
      src: "{{ item }}.j2"
      dest: ../build/{{ item }}
      mode: 0644
    with_items:
      - storageclass.yaml
      - deployment.yaml
  
  - name: Create NFS storageclass, pv and pvc(s)
    shell: kubectl apply -f {{ item }}
    args:
      chdir: ../build
    with_items:
      - storageclass.yaml

  - name: Create nfs csi install.sh file
    template: 
      src: "{{ item }}.j2"
      dest: ../build/{{ item }}
      mode: 0755
    with_items:
      - nfscsiinstall.sh
      - nfscsiuninstall.sh
  
  - name: Install NFS CSI driver
    shell: ./{{item}}
    args:
      chdir: ../build
    with_items:
      - nfscsiinstall.sh
  
  #- name: Install NFS provisioner using helm
  #  include_tasks: helm.yml
    