- name: create project
  shell: ./bmctl create config -c {{ cluster_name}} --enable-apis --create-service-accounts --project-id={{ project_id }}
  args:
    chdir: ~/{{anthos_dir}}
  register: response
  failed_when:
    - response.rc > 1
    - response.rc == 1 and "File exists" not in response.stderr
  
- name: Create project yaml file
  template: 
    src: template.yaml.j2
    dest: ~/{{anthos_dir}}/bmctl-workspace/{{cluster_name}}/{{cluster_name}}.yaml
    mode: 0644

- name: create anthos bm
  shell: ./bmctl create cluster -c {{ cluster_name}}
  args:
    chdir: ~/{{anthos_dir}}
  register: response
- debug:
    msg: "{{response}}"

- name: kubectl get nodes
  shell: kubectl --kubeconfig bmctl-workspace/{{cluster_name}}/{{cluster_name}}-kubeconfig get nodes
  args:
    chdir: ~/{{anthos_dir}}