- hosts: leafs
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.https_proxy}}"
    no_proxy: "{{proxy.no_proxy}}"
  roles:
    - { role: srl/reset-config, tags: reset-config}
    - { role: srl/apply-config, tags: apply-config}