- hosts: localhost
  become: true
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.https_proxy}}"
    no_proxy: "{{proxy.no_proxy}}"
  roles:
    - { role: gcloud-sdk, tags: gcloud-sdk}