- hosts: localhost
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.https_proxy}}"
    no_proxy: "{{proxy.no_proxy}}"
  roles:
    - { role: build, tags: always }
    - { role: paco-parser, tags: paco-parser}