---
  - hosts: bootstrap_external
    gather_facts: yes
    become: yes
    pre_tasks:
        - name: Check for Ansible version 2.2 (minimum)
          assert:
            that: "ansible_version.major == 2 and ansible_version.minor >= 2"
            msg:  "Only Ansible version 2.2 or greater is supported by Fabric-Builder, you are using {{ansible_version.full}}"
        - name: Set build_vars variable
          set_fact:
            build_vars: "{{ build_vars_file | default ('../build_vars.yaml') }}"
        - name: Include build variable files
          include_vars: "{{ build_vars }}"
    roles:
      #- { role: packages, tags: packages}
      #- { role: k8s-underlay, tags: k8s-underlay }

  - hosts: bootstrap_external
    gather_facts: yes
    pre_tasks:
        - name: Check for Ansible version 2.2 (minimum)
          assert:
            that: "ansible_version.major == 2 and ansible_version.minor >= 2"
            msg:  "Only Ansible version 2.2 or greater is supported by Fabric-Builder, you are using {{ansible_version.full}}"
        - name: Set build_vars variable
          set_fact:
            build_vars: "{{ build_vars_file | default ('../build_vars.yaml') }}"
        - name: Include build variable files
          include_vars: "{{ build_vars }}"
    roles:
      #- { role: k8s-env, tags: k8s-env}
      #- { role: k9s, tags: k9s }
      # - { role: helm, tags: helm }
      # - { role: nfs, tags: nfs }
      # - { role: multus, tags: multus }
      - { role: paco/prepare, tags: paco/prepare}
