- name: Create a directory if it does not exist
  file:
    path: /opt/cni/bin
    state: directory

- name: Download cni binaries
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
    dest: /opt/cni/bin/
    remote_src: true

- name: Copy over whereabouts config
  copy:
    src: whereabouts.conf
    dest: /etc/cni/net.d/whereabouts.d/
